services:
  app:
    image: node
    working_dir: /app
    command:
      - tail
      - -f
      - /dev/null
    volumes:
      - .:/app

  cerbos:
    image: "ghcr.io/cerbos/cerbos:0.17.0"
    ports:
      - "3592:3592"
      - "3593:3593"
    volumes:
      - ./cerbos/policies:/policies
      - ./cerbos/tests:/tests
